### ISSUE TITLE
FileCacheProvider - exception while opening invalid Manifest

### ISSUE THREAD

**Issue by TomaszKustra** [TurnerSoftware/CacheTower#264]
### What does the bug do?

Sometimes while closing application when cache dumped to file "Manifest" file is empty with "null" text not "{}" ?
Then after restart cache loader can't deserialize "null" throws exception.

```text
System.NullReferenceException: Object reference not set to an instance of an object.
   at CacheTower.Providers.FileSystem.FileCacheLayer.GetAsync[T](String cacheKey) in /home/runner/work/CacheTower/CacheTower/src/CacheTower/Providers/FileSystem/FileCacheLayer.cs:line 237
   at CacheTower.CacheStack.GetWithLayerIndexAsync[T](String cacheKey) in /home/runner/work/CacheTower/CacheTower/src/CacheTower/CacheStack.cs:line 255
   at CacheTower.CacheStack.GetOrSetAsync[T](String cacheKey, Func`2 valueFactory, CacheSettings settings) in /home/runner/work/CacheTower/CacheTower/src/CacheTower/CacheStack.cs:line 306
   at CacheTower.CacheStack`1.GetOrSetAsync[T](String cacheKey, Func`3 getter, CacheSettings settings) in /home/runner/work/CacheTower/CacheTower/src/CacheTower/CacheStack{TContext}.cs:line 62
```

1. I know there are some valuses in cache but FileProvider don't writes Manifest in proper way.
2. After restart FileProvider want to deserialize "null" and we have exception..

Temporary i fixed this for my project by few lines of code with test for CacheManifest in method TryLoadManifestAsync, but i think fix must be don in other place.

```csharp
private async Task TryLoadManifestAsync()
{
	//Avoid unnecessary lock contention way after manifest is loaded by checking before lock
	if (CacheManifest is null)
	{
		await ManifestLock.WaitAsync();
		try
		{
			//Check that once we have lock (due to a race condition on the outer check) that we still need to load the manifest
			if (CacheManifest is null)
			{
				if (File.Exists(ManifestPath))
				{
					CacheManifest = await DeserializeFileAsync<ConcurrentDictionary<string?, ManifestEntry>>(ManifestPath);
// Temporary Fix start  -----------------------------------------------------------------------------
					if(CacheManifest is null)
					{
						CacheManifest = new ConcurrentDictionary<string?, ManifestEntry>();
						await SerializeFileAsync(ManifestPath, CacheManifest);
					}
// Temporary Fix end -----------------------------------------------------------------------------
				}
				else
				{
					if (!Directory.Exists(Options.DirectoryPath))
					{
						Directory.CreateDirectory(Options.DirectoryPath);
					}

					CacheManifest = new ConcurrentDictionary<string?, ManifestEntry>();
					await SerializeFileAsync(ManifestPath, CacheManifest);
				}
			}
		}
		finally
		{
			ManifestLock.Release();
		}
	}
}
```

### Environment 

- NuGet Package Version: 0.14.0
- .NET Runtime Version:  .NET 7
- Operating System: Windows/Mac/Linux

**Comment by Turnerj** [comment]
Thanks for raising the issue @TomaszKustra - that's a good find, yeah it isn't handling the manifest being `null` from deserialization.
